### ISSUE TITLE
Can be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by sternschnaube** [Nova-Committee/beehave#1]
Tested on Fabric.

**Comment by MUYUTwilighter** [comment]
Can you provide the specific mod version (including MC ver.) you've tested? I'll mark that file compatible with 1.20.2.

A version that is not marked by me does not represents the mod would definetly not work on that version. it actually means I didn't test the mod on specific MC version. Because I have limited effort (subjectively, providing LTS for important versions like final min. ver. is prior), I cannot test every min version of MC.

Besides, with limited effort, I cannot create branches for every minor MC ver. Which means *permanent* yield of a branch works on certain minor versions cannot be ensured, and that's why I would not mark those minor versions.

But don't worry, I would never limit the meta of my mods with specified minor versions, so that users like you can try use these mods on the versions you like, and it's fantastic if it just woks. And more, we like users like you that fullfill the version tags!

**Comment by venaminecraft** [comment]
Latest which is "beenfo-1.20-fabric0.83.0-1.3.3-spigot".
